theme: alembic-jekyll-theme
plugins:
  - jekyll-remote-theme
title: ADAcadabra
description: Lou De Bel-Air, Jiacheng Yang, Mats Hansen Frydenberg
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
