# _config.yml

title: Your Site Title
description: Your site description
url: "https://loudba.github.io/ada-2023-project-adacadabra/"  # Update with your GitHub Pages URL

theme: jekyll-theme-cayman

# Optional settings
author:
  name: Lou

plugins:
  - jekyll-feed

# GitHub Pages settings
repository: LouDBA/ada-2023-project-adacadabra.github.io

