theme: jekyll-theme-minimal
title: ADAcadabra
description: Lou De Bel-Air, Jiacheng Yang, Mats Hansen Frydenberg
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
